### ISSUE TITLE
Factorio 2.0 Support?

### ISSUE THREAD

**Issue by codecnotsupported** [emlun/factorio-blueprint-aligner#2]
[Title]

**Comment by emlun** [comment]
Yes, when I get around to it. I have no concrete timeline for that at the moment.

**Comment by codecnotsupported** [comment]
> Yes, when I get around to it. I have no concrete timeline for that at the moment.

Thank you.

**Comment by emlun** [comment]
Thanks for your patience, 2.0 support is up now!
